name: CI

on:
  push:
    branches:
      - main
      - test
  pull_request:
  schedule:
    - cron: '50 6 * * *'

env:
  rust_toolchain: nightly

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy
      - name: Setup | Std
        run: rustup component add rust-src --toolchain ${{ env.rust_toolchain }}-x86_64-unknown-linux-gnu
      - name: Setup | Default to nightly
        run: rustup default ${{ env.rust_toolchain }}
      - name: Setup | ldproxy
        run: cargo install ldproxy
      - name: Build | Fmt Check
        run: cargo fmt -- --check
      - name: Build | Clippy
        run: cargo clippy --no-deps --target xtensa-esp32-espidf -- -Dwarnings
      - name: Build | Compile
        run: cargo build --target xtensa-esp32-espidf
